### ISSUE TITLE
ob_end_clean();

### ISSUE THREAD

**Issue by jacquestrdx123** [n1crack/vuefinder-php#2]
Hi

This is most likely my own stupidity

I created a route

Route::any('/filesystem', function() {

    $vuefinder = new Ozdemir\VueFinder\VueFinder([
        'local' => Storage::disk('public')->getAdapter(),
    ]);

    $config = [
        'publicLinks' => [
            'local:public' => 'https://jdn.pixelnbyte.com',
        ]
    ];

    $vuefinder->init($config);
});

But when I try to access files I get an error 

Relating to line 495 in VueFinder.php 

            ob_end_clean();

ErrorException: ob_end_clean(): Failed to delete buffer. No buffer to delete in file /cms_rebuild/vendor/ozdemir/vuefinder-php/src/VueFinder.php on line 495

This is hosted locally using VALET. 

But I cannot seem to find the cause of the error. 

If I comment out             //ob_end_clean(); it all seems to work fine

**Comment by n1crack** [comment]
It should be fixed now. thanks.
