### ISSUE TITLE
Adapter Key error

### ISSUE THREAD

**Issue by NinoNikoles** [n1crack/vuefinder-php#7]
Fatal error: Uncaught TypeError: Cannot assign null to property Ozdemir\VueFinder\VueFinder::$adapterKey of type string

In usage file:
$vuefinder = new VueFinder([
    'local' => new LocalFilesystemAdapter(dirname(__DIR__).'/public'),
]);

**Comment by n1crack** [comment]
I think it is here. the request should have "adapter" key..  you can change it as you like 👍 

 

https://github.com/n1crack/vuefinder-php/blob/051d5e8eb8d487cf321a58b7c5775ced16cdfb23/src/VueFinder.php#L42



maybe like this: 

```php
 $this->adapterKey = $this->request->get('adapter') ?? array_keys($storages)[0];
 ```
